<?php echo $this->doctype(); ?>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Administrator '. $this->translate('Admin Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/admin/css/AdminLTE.css')
                        ->prependStylesheet($this->basePath() . '/font-awesome-4.1.0/css/font-awesome.min.css');
                        ?>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/admin/jquery.js'); ?>
    </head>
<body>
<body class="bg-black">
<?php echo $this->content; ?>
<?php echo $this->inlineScript() ?>
	   <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/user/bootstrap.min.js'); ?>

</body>
</html>
