<div class="<?php echo $this->navigation()->menu()->getUlClass(); ?>">
<ul class="nav navbar-nav">
<li class="active"><a href="#">Home</a>
	<ul>
		<li class="active"><a href="#">Level-1</a></li>
		<li class="active"><a href="#">Level-2</a></li>
		<li class="active"><a href="#">Level-3</a></li>
		<li class="active"><a href="#">Level-4</a></li>
	</ul>
</li>
<li class="active"><a href="#">Menu-2</a>
	<ul>
		<li class="active"><a href="#">Level-1</a></li>
		<li class="active"><a href="#">Level-2</a></li>
		<li class="active"><a href="#">Level-3</a></li>
		<li class="active"><a href="#">Level-4</a></li>
	</ul>
</li>
<li class="active"><a href="#">Menu-3</a>
	<ul>
		<li class="active"><a href="#">Level-1</a></li>
		<li class="active"><a href="#">Level-2</a></li>
		<li class="active"><a href="#">Level-3</a></li>
		<li class="active"><a href="#">Level-4</a></li>
	</ul>
</li>
<li class="active"><a href="#">Menu-4</a>
	<ul>
		<li class="active"><a href="#">Level-1</a></li>
		<li class="active"><a href="#">Level-2</a></li>
		<li class="active"><a href="#">Level-3</a></li>
		<li class="active"><a href="#">Level-4</a></li>
	</ul>
</li>

</ul>
</div>

