  <!-- Navigation -->
  
	<?php echo $this->nevigation ?>
	  <div class="col-lg-12">
        <div id="page-wrapper">
            <div class="container-fluid">
				<div class="row">
                    <div class="col-lg-12">
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-edit"></i> Change Password
                            </li>
                        </ol>
                    </div>
                </div>
               <h1>Change Password</h1>
               <?php if(count($flashMessages)) : ?>
				<center><div class="logins" style="width:100%;">
				<?php foreach ($flashMessages as $msg) : ?>
				<div class="<?=$messageClass?>"><?php echo $msg; ?></div>
				<?php endforeach;  ?>
				</div></center>
				<?php endif; ?>
            	<?php
				$form = $this->form;
				$form->setAttribute('action', $this->url('user', array('action' => 'changepasswordupdate')));
				$form->prepare();
				echo $this->form()->openTag($form);
				echo $this->formHidden($form->get('id')); ?>
				<div class="form-group">
					<label class="control-label" for="inputSuccess">Old Passowrd</label>
					<?php echo $this->formRow($form->get('old_password'));?>
				</div>
				
				<div class="form-group">
					<label class="control-label" for="inputSuccess">New Passowrd</label>
					<?php echo $this->formRow($form->get('new_passowrd'));?>
				</div>
				
				<div class="form-group">
					<label class="control-label" for="inputSuccess">Re New Passowrd</label>
					<?php echo $this->formRow($form->get('confirm_new_password'));?>
				</div>
				<?                           
				echo $this->formSubmit($form->get('submit'));
				echo $this->form()->closeTag();
				?>
                
                </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
        </div>
