<!-- Main -->
			<div id="main-wrapper">
				<div id="main" class="container">
					<!--Hightlights Section Start Here-->
					<?php echo $this->header; ?>
					<!--Hightlights Section Start Here-->

					<!--Latest Post Start Here-->
					<?php echo $this->latestPost;?>
					<!--Latest Post ENds Here-->
					<div class="row 200%">
						<div class="12u">

							<!-- Blog -->
								<section class="box blog">
									<h2 class="major"><span>Post Destails</span></h2>
									
									<div>
										<div class="row">
											<div class="9u">
												<div class="content content-left">
												
													<!-- Featured Post -->
														<!--More Post Start Here-->
														<?php  echo $this->allPost;?>
														<!--More Post Ends Here-->
														<br/>
												</div>
											</div>
											
											
											<div class="3u">
												<div class="sidebar">
																								<!-- Archives -->
														<ul class="divided">
                                                        <li><a href="#" class="button alt current">Browse More</a></li>													</ul>
                                                    
														
												
												</div>
											</div>
										</div>
									</div>
								</section>
							
						</div>
					</div>
				</div>
			</div>

		<!-- Footer -->
			<footer id="footer" class="container">
				<?php echo $this->footer_top;?>
				<div class="row 200%">
					<div class="12u">

						<!-- Contact -->
							<section>
								<h2 class="major"><span>Get in touch</span></h2>
								<ul class="contact">
									<li><a class="icon fa-facebook" href="#"><span class="label">Facebook</span></a></li>
									<li><a class="icon fa-twitter" href="#"><span class="label">Twitter</span></a></li>
									<li><a class="icon fa-instagram" href="#"><span class="label">Instagram</span></a></li>
									<li><a class="icon fa-dribbble" href="#"><span class="label">Dribbble</span></a></li>
									<li><a class="icon fa-google-plus" href="#"><span class="label">Google+</span></a></li>
								</ul>
							</section>
					
					</div>
				</div>
<!-- Copyright 
					<div id="copyright">
						<ul class="menu">
							<li></li>
						</ul>
					</div>				
-->


			</footer>
