<!-- Navigation -->
<?php echo $this->nevigation ?>
<div id="page-wrapper">
<div class="container-fluid">
<div class="row">
<div class="col-lg-12">
<ol class="breadcrumb">
    <li>
        <i class="fa fa-dashboard"></i>  <a href="#">Dashboard</a>
    </li>
    <li class="active">
        <i class="fa fa-edit"></i> Edit Post
    </li>
</ol>
</div>
</div>
				<?php if(count($flashMessages)) : ?>
				<center><div class="logins" style="width:100%;">
				<?php foreach ($flashMessages as $msg) : ?>
				<div class="<?=$messageClass?>"><?php echo $msg; ?></div>
				<?php endforeach;  ?>
				</div></center>
				<?php endif; ?>
            	
	<?php
				$form = $this->form;
				$form->setAttribute('action', $this->url('post', array('action' => 'edit')));
				$form->prepare();
				echo $this->form()->openTag($form);
				echo $this->formHidden($form->get('id')); ?>
				<div class="form-group">
					<label class="control-label" for="inputSuccess">Post Title</label>
					<?php echo $this->formRow($form->get('title'));?>
				</div>
				
				<div class="form-group">
					<label class="control-label" for="inputSuccess">Post Description</label>
					<?php echo $this->formRow($form->get('post'));?>
				</div>
   
         		<div class="form-group">
					<label class="control-label" for="inputSuccess">Status</label>
					<?php echo $this->formRow($form->get('status'));?>
				</div>
   
				<?                           
				echo $this->formSubmit($form->get('submit'));
				echo $this->formRow($form->get('Cancel'));
				echo $this->form()->closeTag();
	?>
</div>
<!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->


