<!-- Navigation -->
<?php echo $this->nevigation ?>
<div id="page-wrapper">
<div class="container-fluid">
<div class="row">
<div class="col-lg-12">
<ol class="breadcrumb">
    <li>
        <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a>
    </li>
    <li class="active">
        <i class="fa fa-edit"></i> All Post
    </li>
</ol>
</div>
</div>
	<?php 
 $title = 'All Posts';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <p>
     <a href="<?php echo $this->url('post', array('action'=>'add'));?>">Add New Post</a>
 </p>
	<?php if(count($flashMessages)) : ?>
				<center><div class="logins" style="width:100%;">
				<?php foreach ($flashMessages as $msg) : ?>
				<div class="<?=$messageClass?>"><?php echo $msg; ?></div>
				<?php endforeach;  ?>
				</div></center>
				<?php endif; ?>
            
 <table class="table" width="100%">
 <tr>
     <th>SN</th>
     <th>User</th>
     <th>Title</th>
     <th>Description</th>
     <th>Status</th>
     <th>Created</th>
     <th>Action</th>
 </tr>
 <?php $i=1;foreach ($this->paginator as $post) :
    //echo "<pre>";
    //print_r($post);
    ?>
 <tr id="postRow_<?=$post->id?>">
    <th><?php echo $i;?></th> 
    <td><?php echo $this->escapeHtml($post->first_name);?>&nbsp;
        <?php echo $this->escapeHtml($post->last_name);?></td>
     <td><?php echo substr($this->escapeHtml($post->title),0,25);?>...</td>
     <td><?php echo substr($this->escapeHtml($post->post),0,50);?>...</td>
     <td><?php echo $this->escapeHtml($post->created);?></td>
     <td><?php if($post->status==0){ ?> <font color="green"><b>Published</b></font><?php }else{ ?> <font color="red"><b>Un-Published</b></font> <?php } ?> </td>
     <td>
         <a href="<?php echo $this->url('post',
             array('action'=>'edit', 'id' => $post->id));?>">Edit</a> |
         <a href="javascript:void(0)" onclick="deletePost(<?php echo $post->id;?>)">Delete</a>
     </td>
 </tr>
 <?php $i++; endforeach; ?>
</table>
<table width="100%">
<tr>
   <td align="left">
       <?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->paginator,
     // the scrolling style "Elastic","All","Jumping","Sliding"
     'Jumping',
     // the partial to use to render the control
     array('partial/jumping.phtml', 'Post'),
     // the route to link to when a user clicks a control link
     array(
         'route' => 'post'
     )
 );
 ?>
   </td>
   <td align="center">
    <?php echo $this->paginationControl(
                                    $this->paginator,
                                    'Jumping',
                                    array('partial/search.phtml', 'Post'),
                                    array('route' => 'post')
                           );
       ?>
 </td>
   <td align="right">
       <?php echo $this->paginationControl(
                                    $this->paginator,
                                    'Jumping',
                                    array('partial/paginator.phtml', 'Post'),
                                    array('route' => 'post')
                           );
       ?>
   </td>
</tr>
 </table>
</div>
            <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
<script>
jQuery.noConflict();
function deletePost(e){
var cnf=confirm("Are you sure, you want to delete this post.\nAll associated data will be deleted permanently.");if(cnf){   
jQuery.ajax({
			type: "POST",
			url: "<?php echo $this->basePath('/post/delete'); ?>",
			data: "id="+e,
            cache: false,
            async: true,
			error: function(jqXHR, exception){
				if (jqXHR.status === 0){
					alert('Not connect.\n Verify Network.');
				}else if (jqXHR.status == 404){
					alert('Requested page not found. [404]');
				}else if (jqXHR.status == 500){
					alert('Internal Server Error [500].');
				}else if (exception === 'parsererror'){
					alert('Requested JSON parse failed.');
				}else if (exception === 'timeout'){
					alert('Time out error.');
				}else if (exception === 'abort'){
					alert('Ajax request aborted.');
				}else{
					alert('Uncaught Error.\n' + jqXHR.responseText);
				}
			},

			beforeSend:function(){
						jQuery('#postRow_'+e).css('background-color','#ff0000');
					  },
			success: function(response){
                     if(response==1){
                        jQuery('#postRow_'+e).fadeOut();
                     }else{
                        alert(response);
                     }
            }
		});
}else{
   return false;
}
}
</script>


