<?php 
if(!empty($this->post)){ 
	$data=$this->post;
       //print_r($data);?>
<article class="box post">
<header>
   <h3  style="text-decoration: none !important;"><p  style="text-decoration: none !important;"><a href="#" style="text-decoration: none !important;text-transform: none;font-family: sans-serif; font-size: 36px;font-weight:bold"><?php echo $data->title; ?></a></p></h3>
	<ul class="meta">
	   <li class="icon fa-user-o">By: <?php echo $data->first_name; ?>&nbsp;<?php echo $data->last_name; ?></li>
       <li class="icon fa-clock-o"><?php echo $data->created; ?></li>
		<li class="icon fa-comments"><a href="#">8</a></li>
	</ul>
</header>
<a href="#" class="image featured"><img src="<?php echo $this->basePath()?>/img/Front/post_img/<?php echo $data->images;?>" alt="" /></a>
<p style="text-transform: none;font-family: sans-serif; font-size: 14px;">
<?php echo nl2br($data->post); ?>
</p>
</br>
</article>
<br/>
<?php } ?>
