<!-- Main -->
			<div id="main-wrapper">
				<div id="main" class="container">
					<!--Hightlights Section Start Here-->
					<?php echo $this->header; ?>
					<!--Hightlights Section Start Here-->

					<!--Latest Post Start Here-->
					<?php echo $this->latestPost;?>
					<!--Latest Post ENds Here-->
					<div class="row 200%">
						<div class="12u">

							<!-- Blog -->
								<section class="box blog">
									<h2 class="major"><span>Post Destails</span></h2>
									
									<div>
										<div class="row">
											<div class="9u">
												<div class="content content-left">
												
													<!-- Featured Post -->
														<!--More Post Start Here-->
														<?php  echo $this->morepost;?>
														<!--More Post Ends Here-->
														<br/>
														<div class="row 100%">
															<div class="12u">
																<?php echo $this->commentPost;?>
															</div>
														</div>
												
												</div>
											</div>
											
											
											
											<div class="3u">
												<div class="sidebar">
											
													<!-- Archives -->
														<ul class="divided">
															<?php
                                                            foreach($this->paginator as $datas){?>
                                                           <li>
																<article class="box post-summary">
																	<h3><a style="text-transform: none;font-family: sans-serif; font-size: 13px;font-weight:bold" href="<?php echo $this->url('post'); ?>view/<?php echo $datas->id; ?>"><?php echo $datas->title;?></a></h3>
                                                                    <p></p><a href="<?php echo $this->url('post'); ?>view/<?php echo $datas->id; ?>" class="image featured">
<img src="<?php echo $this->basePath()?>/img/Front/post_img/<?php echo $datas->images?>" alt="" width="280px" height="160"/></a></p>
                                                                    
                                                                    <p style="font-size:13px"><?php echo substr($datas->post,0,100);?></p>
                                                                    <br/>
																	<ul class="meta">
																		<li class="icon fa-clock-o">6 hours ago</li>
																		<li class="icon fa-comments"><a href="#">34</a></li>
																	</ul>
																</article>
															</li>
                                                            <?php } ?>
                                                            <li><a href="<?php echo $this->url('post'); ?>all" class="button alt current">Browse More</a></li>
														</ul>
														
												</div>
											</div>
										</div>
									</div>
								</section>
							
						</div>
					</div>
				</div>
			</div>

		<!-- Footer -->
			<footer id="footer" class="container">
				<?php echo $this->footer_top;?>
				<div class="row 200%">
					<div class="12u">

						<!-- Contact -->
							<section>
								<h2 class="major"><span>Get in touch</span></h2>
								<ul class="contact">
									<li><a class="icon fa-facebook" href="#"><span class="label">Facebook</span></a></li>
									<li><a class="icon fa-twitter" href="#"><span class="label">Twitter</span></a></li>
									<li><a class="icon fa-instagram" href="#"><span class="label">Instagram</span></a></li>
									<li><a class="icon fa-dribbble" href="#"><span class="label">Dribbble</span></a></li>
									<li><a class="icon fa-google-plus" href="#"><span class="label">Google+</span></a></li>
								</ul>
							</section>
					
					</div>
				</div>
<!-- Copyright 
					<div id="copyright">
						<ul class="menu">
							<li></li>
						</ul>
					</div>				
-->


			</footer>
