<div class="wrapper row-offcanvas row-offcanvas-left">
   <!-- Left side column. contains the logo and sidebar -->
          
			
            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">                
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                       <?php echo $title;
                       $this->headTitle($title);?>
                        <small> Website Users</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="dashboard.html"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active"><?php echo $this->escapeHtml('Manage User');?></li>
                    </ol>
                </section>

                <!-- Main content -->
                   <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title"><?php echo $this->escapeHtml('All User List');?>
                                    <small> <?php echo $this->escapeHtml('Add New User');?></small>
                                    </h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                   	<?php if(count($flashMessages)) : ?>
				<center><div class="logins" style="width:100%;">
				<?php foreach ($flashMessages as $msg) : ?>
				<div class="<?=$messageClass?>"><?php echo $msg; ?></div>
				<?php endforeach;  ?>
				</div></center>
				<?php endif; ?>
            
 <table id="example1" class="table table-bordered table-striped datatable1" width="100%">
 <tr>
     <th>SN</th>
     <th>User</th>
     <th>Title</th>
     <th>Description</th>
     <th>Status</th>
     <th>Created</th>
     <th>Action</th>
 </tr>
 <?php $i=1;foreach ($this->paginator as $post) :
    //echo "<pre>";
    //print_r($post);
    ?>
 <tr id="postRow_<?=$post->id?>">
    <th><?php echo $i;?></th> 
    <td><?php echo $this->escapeHtml($post->first_name);?>&nbsp;
        <?php echo $this->escapeHtml($post->last_name);?></td>
     <td><?php echo substr($this->escapeHtml($post->title),0,25);?>...</td>
     <td><?php echo substr($this->escapeHtml($post->post),0,50);?>...</td>
     <td><?php echo $this->escapeHtml($post->created);?></td>
     <td><?php if($post->status==0){ ?> <font color="green"><b>Published</b></font><?php }else{ ?> <font color="red"><b>Un-Published</b></font> <?php } ?> </td>
     <td>
         <a href="<?php echo $this->url('post',
             array('action'=>'edit', 'id' => $post->id));?>">Edit</a> |
         <a href="javascript:void(0)" onclick="deletePost(<?php echo $post->id;?>)">Delete</a>
     </td>
 </tr>
 <?php $i++; endforeach; ?>
</table>
<table width="100%">
<tr>
   <td align="left">
       <?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->paginator,
     // the scrolling style "Elastic","All","Jumping","Sliding"
     'Jumping',
     // the partial to use to render the control
     array('partial/jumping.phtml', 'Post'),
     // the route to link to when a user clicks a control link
     array(
         'route' => 'post'
     )
 );
 ?>
   </td>
   <td align="center">
    <?php echo $this->paginationControl(
                                    $this->paginator,
                                    'Jumping',
                                    array('partial/search.phtml', 'Post'),
                                    array('route' => 'post')
                           );
       ?>
 </td>
   <td align="right">
       <?php echo $this->paginationControl(
                                    $this->paginator,
                                    'Jumping',
                                    array('partial/paginator.phtml', 'Post'),
                                    array('route' => 'post')
                           );
       ?>
   </td>
</tr>
 </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                    </div>

                </section><!-- /.content -->
            </aside><!-- /.right-side -->

        </div><!-- ./wrapper -->
<?php $this->inlineScript()->captureStart(); ?>
function delUser(e){
  if(confirm('Are you sure that you want to delete this user')){
   $.ajax({
			type: "POST",
			url: "<?=$this->basePath()?>/admin/user/user/delete/"+e,
			data: "e="+e,
			error: function(jqXHR, exception){
				if (jqXHR.status === 0){
					alert('Not connect.\n Verify Network.');
				}else if (jqXHR.status == 404){
					alert('Requested page not found. [404]');
				}else if (jqXHR.status == 500){
					alert('Internal Server Error [500].');
				}else if (exception === 'parsererror'){
					alert('Requested JSON parse failed.');
				}else if (exception === 'timeout'){
					alert('Time out error.');
				}else if (exception === 'abort'){
					alert('Ajax request aborted.');
				}else{
					alert('Uncaught Error.\n' + jqXHR.responseText);
				}
			},

			beforeSend:function(){
						var bSend = '<center>loading.... </center>'; 
								$('#row_'+e).css('background-color','#FFD200');
					      },
            success: function(response){
                        if(response=='YES'){
                           $('#row_'+e).fadeOut();
                        }else{
                           $('#row_'+e).css('background-color','#FFFFFF');
                        }
						}
		});
        }
 
        
}        
<?php $this->inlineScript()->captureEnd(); ?>


