  <aside class="left-side sidebar-offcanvas">                
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="<?php echo SITEPATH; ?>/img/admin/img/avatar3.png" class="img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left">
                            <p>Hello, 
					<?php   $adminHelperObj=$this->admin_helper();
						echo $adminHelperObj->AuthIndentities()->first_name;
					?>
			    </p>
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                    <!-- search form -->
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Search..."/>
                            <span class="input-group-btn">
                                <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                     <?php  $this->navigation('navigation')->menu()
                            ->setPartial('admin/partials/leftmenu');
                       echo $this->navigation()->menu()->render();
                    ?>
                </section>
                <!-- /.sidebar -->
            </aside>
