<ul class="sidebar-menu">
   <li class="active">
      <a href="<?php echo $this->basePath('/admin'); ?>">
         <i class="fa fa-dashboard"></i> <span>Dashboard</span>
      </a>
   </li>

   <li class="treeview">
      <a href="#">
         <i class="fa fa-edit"></i> <span>Static Page Manager</span>
         <i class="fa fa-angle-left pull-right"></i>
      </a>
      <ul class="treeview-menu">
         <li><a href="viewallpages.html"><i class="fa fa-angle-double-right"></i> View all pages</a></li>
         <li><a href="editors.html"><i class="fa fa-angle-double-right"></i> Editors</a></li>
      </ul>
   </li>
   <li class="treeview">
      <a href="#">
         <i class="fa fa-edit"></i> <span>Manager Users</span>
         <i class="fa fa-angle-left pull-right"></i>
      </a>
      <ul class="treeview-menu">
         <li>
            <a href="<?php echo $this->basePath('/admin/user/user'); ?>">
               <i class="fa fa-angle-double-right"></i>View all users</a>
         </li>
         <li>
            <a href="<?php echo $this->url('user', array('action' => 'add')); ?>">
               <i class="fa fa-angle-double-right"></i>Add New User</a>
         </li>
      </ul>
   </li>
   <li class="treeview">
      <a href="#">
         <i class="fa fa-table"></i> <span>Manage Post</span>
         <i class="fa fa-angle-left pull-right"></i>
      </a>
      <ul class="treeview-menu">
         <li>
            <a href="<?php echo $this->basePath('/admin/post/post'); ?>">
               <i class="fa fa-angle-double-right"></i>View All Post</a>
         </li>
      </ul>
   </li>
 </ul>
