<?php echo $this->doctype(); ?>
<meta charset="utf-8">
<?php echo $this->headTitle('Administrator '. $this->translate('Admin Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php echo $this->headMeta()
	->appendName('viewport', 'width=device-width, initial-scale=1.0')
	->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<!-- Le styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
				->prependStylesheet($this->basePath() . '/css/admin/css/morris.css')
				->prependStylesheet($this->basePath() . '/css/admin/css/AdminLTE.css')
				->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
				->prependStylesheet('//code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css')
				->prependStylesheet($this->basePath() . '/font-awesome-4.1.0/css/font-awesome.min.css');
				?>
</head>
<body class="skin-blue">
<?php echo $this->content; ?>
<?php echo $this->inlineScript() ?>
<!-- Scripts -->
<?php echo $this->headScript()
->prependFile($this->basePath() . '/js/admin/js/app.js') 
->prependFile($this->basePath() . '/js/admin/js/morris.min.js')
->prependFile('//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js') 
->prependFile($this->basePath() . '/js/admin/js/bootstrap.min.js') 
->prependFile($this->basePath() . '/js/admin/js/jquery.min.js'); ?>
<script type="text/javascript">
			$(function() {
				"use strict";
				// AREA CHART
                var area = new Morris.Area({
                    element: 'revenue-chart',
                    resize: true,
                    data: [
                        {y: '2011 Q1', item1: 2666, item2: 2666},
                        {y: '2011 Q2', item1: 2778, item2: 2294},
                        {y: '2011 Q3', item1: 4912, item2: 1969},
                        {y: '2011 Q4', item1: 3767, item2: 3597},
                        {y: '2012 Q1', item1: 6810, item2: 1914},
                        {y: '2012 Q2', item1: 5670, item2: 4293},
                        {y: '2012 Q3', item1: 4820, item2: 3795},
                        {y: '2012 Q4', item1: 15073, item2: 5967},
                        {y: '2013 Q1', item1: 10687, item2: 4460},
                        {y: '2013 Q2', item1: 8432, item2: 5713}
                    ],
                    xkey: 'y',
                    ykeys: ['item1', 'item2'],
                    labels: ['Item 1', 'Item 2'],
                    lineColors: ['#a0d0e0', '#3c8dbc'],
                    hideHover: 'auto'
                });
				
			});
		</script>
</body>
</html>
