<!DOCTYPE HTML>
<!--
	TXT by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
 	    <?php echo $this->headTitle('ZF2 '. $this->translate('ZF2 Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		  <!-- Scripts -->
        <?php echo $this->headScript()
			->prependFile($this->basePath() . '/js/Front/js/init.js')
            ->prependFile($this->basePath() . '/js/Front/js/skel-layers.min.js')
            ->prependFile($this->basePath() . '/js/Front/js/skel.min.js')
            ->prependFile($this->basePath() . '/js/Front/js/jquery.dropotron.min.js')
            ->prependFile($this->basePath() . '/js/Front/js/jquery.min.js');
        ?>
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/Front/css/skel.css')
                        ->prependStylesheet($this->basePath() . '/css/Front/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/Front/css/style-desktop.css') ?>
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
	</head>
<body class="homepage">
	 <?php echo $this->content; ?>
</body>
</html>
