
		<!-- Banner -->
			<div id="banner-wrapper">
				<section id="banner">
					<h2>Welcome to ZF2 Blogging</h2>
					<p>A full feature User, Admin, Blog Module</p>
					<a href="<?php echo $this->url('post') ?>" class="button">Alright let's go</a>
				</section>
			</div>

		<!-- Main -->
			<div id="main-wrapper">
				<div id="main" class="container">
					<!--Hightlights Section Start Here-->
					<?php echo $this->header; ?>
					<!--Hightlights Section Start Here-->

					<!--Latest Post Start Here-->
					<?php echo $this->latestPost;?>
					<!--Latest Post ENds Here-->
					<div class="row 200%">
						<div class="12u">

							<!-- Blog -->
								<section class="box blog">
									<h2 class="major"><span>Latest Headline</span></h2>
									
									<div>
										<div class="row">
											<div class="9u">
												<div class="content content-left">
												
													<!-- Featured Post -->
														<!--More Post Start Here-->
														<?php echo $this->morepost;?>
														<!--More Post Ends Here-->
														<br/>
												</div>
											</div>
											
											
											<div class="3u">
												<div class="sidebar">
											
													<!-- Archives -->
														<ul class="divided">
															<li>
																<article class="box post-summary">
																	<h3><a href="#">A Subheading</a></h3>
																	<ul class="meta">
																		<li class="icon fa-clock-o">6 hours ago</li>
																		<li class="icon fa-comments"><a href="#">34</a></li>
																	</ul>
																</article>
															</li>
															<li>
																<article class="box post-summary">
																	<h3><a href="#">Another Subheading</a></h3>
																	<ul class="meta">
																		<li class="icon fa-clock-o">9 hours ago</li>
																		<li class="icon fa-comments"><a href="#">27</a></li>
																	</ul>
																</article>
															</li>
															<li>
																<article class="box post-summary">
																	<h3><a href="#">And Another</a></h3>
																	<ul class="meta">
																		<li class="icon fa-clock-o">Yesterday</li>
																		<li class="icon fa-comments"><a href="#">184</a></li>
																	</ul>
																</article>
															</li>
															<li>
																<article class="box post-summary">
																	<h3><a href="#">And Another</a></h3>
																	<ul class="meta">
																		<li class="icon fa-clock-o">2 days ago</li>
																		<li class="icon fa-comments"><a href="#">286</a></li>
																	</ul>
																</article>
															</li>
															<li>
																<article class="box post-summary">
																	<h3><a href="#">And One More</a></h3>
																	<ul class="meta">
																		<li class="icon fa-clock-o">3 days ago</li>
																		<li class="icon fa-comments"><a href="#">8,086</a></li>
																	</ul>
																</article>
															</li>
														</ul>
														<a href="#" class="button alt">Browse Archives</a>
												
												</div>
											</div>
										</div>
									</div>
								</section>
							
						</div>
					</div>
				</div>
			</div>

		<!-- Footer -->
			<footer id="footer" class="container">
				<?php echo $this->footer_top;?>
				<div class="row 200%">
					<div class="12u">

						<!-- Contact -->
							<section>
								<h2 class="major"><span>Get in touch</span></h2>
								<ul class="contact">
									<li><a class="icon fa-facebook" href="#"><span class="label">Facebook</span></a></li>
									<li><a class="icon fa-twitter" href="#"><span class="label">Twitter</span></a></li>
									<li><a class="icon fa-instagram" href="#"><span class="label">Instagram</span></a></li>
									<li><a class="icon fa-dribbble" href="#"><span class="label">Dribbble</span></a></li>
									<li><a class="icon fa-google-plus" href="#"><span class="label">Google+</span></a></li>
								</ul>
							</section>
					
					</div>
				</div>
<!-- Copyright 
					<div id="copyright">
						<ul class="menu">
							<li></li>
						</ul>
					</div>				
-->


			</footer>
